### ISSUE TITLE
AssertionError: image is None

### ISSUE THREAD

**Issue by ZJSYo** [yeyupiaoling/Pytorch-MTCNN#6]
我在原数据集上添加了仿照格式添加了一部分数据集，在训练PNet时候出现报错
Traceback (most recent call last):
  File "/home/huawei/zjs/Pytorch-MTCNN/train_PNet/train_PNet.py", line 51, in <module>
    for batch_id, (img, label, bbox, landmark) in enumerate(train_loader):
  File "/home/huawei/anaconda3/envs/dev/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/huawei/anaconda3/envs/dev/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/huawei/anaconda3/envs/dev/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/huawei/anaconda3/envs/dev/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "../utils/data.py", line 90, in __getitem__
    img = process(img)
  File "../utils/data.py", line 62, in process
    assert (image is not None), 'image is None'
AssertionError: image is None

**Comment by yeyupiaoling** [comment]
图片为空，你看一下是不是自己弄错了路径什么的。

**Comment by ZJSYo** [comment]
增加的数据集图片我是放在lfw_5590目录下，标签数据(path,x1,x2,y1,y2,5 landmarks)添加入了trainImageList。我添加的数据集为.png后缀，这会不会影响。或是说标签数据还需要加入testImageList

**Comment by yeyupiaoling** [comment]
我也不确定你这样是不是正常加入了。

**Comment by ZJSYo** [comment]
> 我也不确定你这样是不是正常加入了。

好的谢谢
